import type { EpochDate } from './dates'
import type { Candle, MarketDataSnapshot } from './market-data'
import type { Order, Position, StockSymbol } from './orders'

/**
 * Market data provided to agents for analysis.
 * Contains price history and current market state.
 */
export interface MarketData {
  /** Trading pair symbol */
  readonly symbol: StockSymbol
  /** Data timestamp */
  readonly timestamp: Date
  /** Current market price */
  readonly price: number
  /** Historical candles for technical analysis */
  readonly candles: readonly Candle[]
  /** Trading volume */
  readonly volume: number
}

/**
 * Result of a completed trade for agent performance tracking.
 * Used to update agent weights and improve decision making.
 */
export interface TradeResult {
  /** Unique order identifier */
  readonly orderId: string
  /** Trade direction */
  readonly side: 'buy' | 'sell'
  /** Entry price of the trade */
  readonly entryPrice: number
  /** Exit price of the trade */
  readonly exitPrice: number
  /** Trade size/quantity */
  readonly size: number
  /** Absolute profit/loss amount */
  readonly pnl: number
  /** Trading fees paid */
  readonly fees: number
  /** Profit/loss as percentage */
  readonly profitPercent: number
  /** Trade duration in milliseconds */
  readonly duration: number
  /** Unix timestamp of trade completion */
  readonly timestamp: EpochDate
}

/**
 * Types of trading agents in the system.
 * Each agent specializes in different market analysis.
 */
export type AgentType =
  /** Analyzes price volatility for trail distance */
  | 'volatility'
  /** Detects momentum and divergences */
  | 'momentum'
  /** Analyzes volume patterns and whale activity */
  | 'volume'
  /** Identifies support/resistance levels */
  | 'market-structure'
  /** Classifies market conditions */
  | 'regime'
  /** Adjusts for stale price data */
  | 'time-decay'
  /** Analyzes bid-ask spread dynamics */
  | 'microstructure'
  /** Cross-asset correlation signals */
  | 'correlation'
  /** Market sentiment analysis */
  | 'sentiment'
  /** AI-powered pattern recognition */
  | 'ai-pattern'
  /** Market entropy measurement */
  | 'entropy'
  /** Swarm intelligence consensus */
  | 'swarm'
  /** Harmonic pattern detection */
  | 'harmonic'
  /** Market topology analysis */
  | 'topology'
  /** Fractal pattern recognition */
  | 'fractal'
  /** Quantum-inspired optimization */
  | 'quantum'

/** Signal strength levels for agent recommendations */
export type SignalStrength = 'strong-buy' | 'buy' | 'neutral' | 'sell' | 'strong-sell'

/**
 * Trading signal generated by an agent.
 * Core output of agent analysis.
 */
export interface AgentSignal {
  /** Unique identifier of the agent */
  readonly agentId: string
  /** Recommended trading action */
  readonly action: 'TRAIL_BUY' | 'TRAIL_SELL' | 'HOLD'
  /** Confidence level (0-1) in the signal */
  readonly confidence: number
  /** Recommended trail distance as percentage */
  readonly trailDistance: number
  /** Detailed reasoning for the signal */
  readonly reasoning: Record<string, unknown>
  /** Signal urgency level */
  readonly urgency?: 'low' | 'medium' | 'high'
}

/**
 * Individual agent vote in consensus decision.
 * Aggregated to determine final trading action.
 */
export interface AgentVote {
  /** Type of agent casting the vote */
  readonly agent: AgentType
  /** Recommended action */
  readonly action: 'buy' | 'sell' | 'hold'
  /** Confidence in recommendation (0-1) */
  readonly confidence: number
  /** Suggested position size */
  readonly size?: number
  /** Suggested entry price */
  readonly price?: number
  /** Suggested stop loss level */
  readonly stopLoss?: number
  /** Suggested take profit level */
  readonly takeProfit?: number
}

/**
 * Aggregated consensus from all agents.
 * Used to make final trading decisions.
 */
export interface AgentConsensus {
  /** Unix timestamp of consensus */
  readonly timestamp: EpochDate
  /** All agent votes */
  readonly votes: readonly AgentVote[]
  /** Final consensus decision */
  readonly decision: 'buy' | 'sell' | 'hold'
  /** Aggregate confidence level */
  readonly confidence: number
  /** Level of disagreement among agents (0-1) */
  readonly dissent: number
}

/**
 * Configuration for an individual agent.
 * Controls agent behavior and influence.
 */
export interface AgentConfig {
  /** Agent type identifier */
  readonly type: AgentType
  /** Whether agent is active */
  readonly enabled: boolean
  /** Weight in consensus (0-1) */
  readonly weight: number
  /** Agent-specific parameters */
  readonly parameters: Record<string, unknown>
}

/**
 * Performance metrics for an agent.
 * Used for weight adjustment and monitoring.
 */
export interface AgentPerformance {
  /** Agent type identifier */
  readonly agent: AgentType
  /** Total signals generated */
  readonly signals: number
  /** Signal accuracy (0-1) */
  readonly accuracy: number
  /** Total profit generated */
  readonly profit: number
  /** Sharpe ratio */
  readonly sharpe: number
  /** Maximum drawdown percentage */
  readonly maxDrawdown: number
  /** Unix timestamp of last update */
  readonly updatedAt: number
}

/**
 * Core interface that all trading agents must implement.
 * Defines the contract for agent lifecycle and behavior.
 */
export interface ITradeAgent {
  /** Unique agent instance ID */
  readonly id: string
  /** Human-readable agent name */
  readonly name: string
  /** Agent version for compatibility */
  readonly version: string

  /**
   * Initialize agent with context.
   * Called once before agent starts analyzing.
   */
  initialize(context: AgentContext): Promise<void>

  /**
   * Gracefully shutdown agent.
   * Clean up resources and save state.
   */
  shutdown(): Promise<void>

  /**
   * Analyze market data and generate trading signal.
   * Core function called on each market update.
   */
  analyze(market: MarketData): Promise<AgentSignal>

  /**
   * Update agent performance based on trade result.
   * Used for learning and weight adjustment.
   */
  updatePerformance(result: TradeResult): void

  /**
   * Get current agent state.
   * Used for persistence and monitoring.
   */
  getState(): AgentState

  /**
   * Restore agent state.
   * Used for recovery after restart.
   */
  setState(state: AgentState): void
}

/**
 * Context provided to agents for initialization and analysis.
 * Contains current market state and trading position.
 */
export interface AgentContext {
  /** Trading pair symbol */
  readonly symbol: StockSymbol
  /** Current unix timestamp */
  readonly timestamp: EpochDate
  /** Current market price */
  readonly currentPrice: number
  /** Historical price candles */
  readonly candles: readonly Candle[]
  /** Current position if any */
  readonly position?: Position
  /** Currently open orders */
  readonly openOrders: readonly Order[]
  /** Complete market snapshot */
  readonly marketData?: MarketDataSnapshot
}

/**
 * Internal state of an agent.
 * Used for persistence and recovery.
 */
export interface AgentState {
  /** Agent type identifier */
  readonly type: AgentType
  /** Whether agent is currently active */
  readonly isActive: boolean
  /** Most recent signal generated */
  readonly lastSignal?: AgentSignal
  /** Performance metrics */
  readonly performance: AgentPerformance
  /** Agent configuration */
  readonly config: AgentConfig
}
